[profile.default]
src = "contracts/src"
out = "contracts/out"
test = "contracts/test"
script = "contracts/script"
libs = ["lib"]
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
studionet = "https://studio.genlayer.com/api"
genlayer = "https://rpc-bradbury.genlayer.com"

[etherscan]
genlayer = { key = "genlayer", url = "https://explorer-bradbury.genlayer.com" }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "params_first"
sort_imports = true
